In [40]:
import pandas as pd
import warnings

warnings.simplefilter(action='ignore', category=UserWarning)
warnings.simplefilter(action='ignore', category=FutureWarning)
warnings.simplefilter(action='ignore', category=pd.errors.SettingWithCopyWarning)

data_basepath = '..\\data\\spain_dataframes\\'

In [41]:
# Leer el fichero con los datos
df = pd.read_csv(f'{data_basepath}datos_tratados.csv')
df

,comunidad_autonoma,edad,genero,actividad_fisica,asistencia_cine,asistencia_directos,asistencia_cultural,asistencia_deporte,dias_alta_contaminacion,homicidios_100mhabit,criminalidad_1000habit,estudios,estado_civil,horasTrabajadas_mes,salario_anual,satisf_hospitales,satisf_dentistas,satisf_especialistas,satisf_medGeneral,frecuencia_felicidad
0,Extremadura,10,hombre,nivel_alto,no,no_puede,no,no,3.3774,0.0000,35.1452,primero_secundaria,casado/a,174.4208,19251.3510,hospitales_satisfecho/a,dentistas_muy_satisfecho/a,especialistas_insatisfecho/a,medGeneral_satisfecho/a,muy_a_menudo
1,Extremadura,18,mujer,nivel_alto,no,no,no_puede,no,1.4413,0.3082,27.8585,educacion_superior,casado/a,127.4882,23284.5483,hospitales_insatisfecho/a,dentistas_satisfecho/a,especialistas_satisfecho/a,medGeneral_satisfecho/a,algunas_veces
2,Extremadura,41,hombre,nivel_bajo,no,si,si,no,6.7861,0.0408,21.3189,primaria,soltero/a,153.6451,21607.6075,hospitales_satisfecho/a,dentistas_muy_satisfecho/a,especialistas_satisfecho/a,medGeneral_satisfecho/a,muy_a_menudo
3,Extremadura,17,mujer,nivel_alto,si,no,no,no,2.5476,0.5331,9.8100,primero_secundaria,soltero/a,132.2961,29640.1647,hospitales_insatisfecho/a,dentistas_neutral,especialistas_satisfecho/a,medGeneral_satisfecho/a,muy_a_menudo
4,Extremadura,75,hombre,nivel_bajo,no,no,si,si,4.7876,0.2332,38.9624,segundo_secundaria_general,soltero/a,131.8787,17538.1113,hospitales_satisfecho/a,dentistas_satisfecho/a,especialistas_insatisfecho/a,medGeneral_satisfecho/a,muy_a_menudo
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,Ceuta,67,mujer,nivel_bajo,no,si,no,no,3.0801,5.6225,44.4724,primaria,soltero/a,125.0744,27052.8314,hospitales_neutral,dentistas_neutral,especialistas_insatisfecho/a,medGeneral_muy_satisfecho/a,muy_a_menudo
19996,Ceuta,61,hombre,nivel_alto,no,no,si,no,5.4394,6.2117,31.6865,primaria,soltero/a,139.3246,27063.6210,hospitales_neutral,dentistas_muy_satisfecho/a,especialistas_muy_satisfecho/a,medGeneral_satisfecho/a,muy_a_menudo
19997,Ceuta,19,hombre,nivel_bajo,no,no,si,no,1.4983,6.0124,48.1812,primaria,soltero/a,161.5733,26024.0808,hospitales_satisfecho/a,dentistas_neutral,especialistas_muy_satisfecho/a,medGeneral_satisfecho/a,algunas_veces
19998,Ceuta,18,mujer,nivel_bajo,no,no,no,no,2.3925,5.9447,60.7626,primero_secundaria,soltero/a,124.3620,19273.6664,hospitales_satisfecho/a,dentistas_satisfecho/a,especialistas_satisfecho/a,medGeneral_muy_satisfecho/a,algunas_veces
19999,Ceuta,46,hombre,nivel_bajo,no_puede,no,no,no,2.2897,6.0490,47.9309,primero_secundaria,casado/a,187.4088,27875.2017,hospitales_neutral,dentistas_muy_satisfecho/a,especialistas_satisfecho/a,medGeneral_muy_satisfecho/a,muy_a_menudo

### Homicidios y Criminalidad --> Percepción de seguridad

Se establece una nota media de la percepción de la seguridad para cada individuo, en función de la media de las notas de los homicidios y la criminalidad.

In [42]:
# Valoración de una columna dentro de un rango determinado
def valorate_numeric_column(df, column_name, new_column_name, min_rank_value=0, max_rank_value=1, revert_rank_valoration=False):
    """
    Normaliza los valores de una columna de un DataFrame dentro de un rango específico y crea una nueva columna con los resultados.

    La valoración se realiza de forma lineal, permitiendo definir un rango mínimo y máximo.
    Se toman como valores extremos los valores mínimo y máximo de la columna especificada en 'column_name'.

    Parámetros:
    -----------
    df : pandas.DataFrame
        DataFrame que contiene la columna a normalizar.
    column_name : str
        Nombre de la columna que se va a normalizar.
    new_column_name : str
        Nombre de la nueva columna donde se almacenarán los valores normalizados.
    min_rank_value : float, opcional (por defecto=0)
        Valor mínimo del rango.
    max_rank_value : float, opcional (por defecto=1)
        Valor máximo del rango.
    revert_rank_valoration : bool, opcional (por defecto=False)
        Si es True, invierte la valoración (el valor más alto se convierte en el más bajo y viceversa).

    Retorna:
    --------
    None. Modifica el DataFrame original añadiendo una nueva columna con los valores normalizados.
    """
    # Valores extremos del dataframe
    min_val = df[column_name].min()
    max_val = df[column_name].max()

    # Proporcionalidad entre el rango definido y el rango calculado
    rank_diference = max_rank_value - min_rank_value

    # Aplicar la fórmula de normalización lineal
    if not revert_rank_valoration:
        df[new_column_name] = ((df[column_name] - min_val) / (max_val - min_val)) * rank_diference + min_rank_value
    else:
        df[new_column_name] = (1 - ((df[column_name] - min_val) / (max_val - min_val))) * rank_diference + min_rank_value

In [43]:
# Valoración de la criminalidad
valorate_numeric_column(df, 'criminalidad_1000habit', 'valoracion_criminalidad', 0, 10, True)

# Valoración de la tasa de homicidios
valorate_numeric_column(df, 'homicidios_100mhabit', 'valoracion_homicidios', 0, 10, True)

df[['criminalidad_1000habit', 'valoracion_criminalidad', 'homicidios_100mhabit', 'valoracion_homicidios']].head()

,criminalidad_1000habit,valoracion_criminalidad,homicidios_100mhabit,valoracion_homicidios
0,35.1452,6.521951,0.0000,10.000000
1,27.8585,7.243059,0.3082,9.510887
2,21.3189,7.890233,0.0408,9.935250
3,9.8100,9.029180,0.5331,9.153971
4,38.9624,6.144192,0.2332,9.629912

In [44]:
# Hacer una valoración media "percepcion_seguridad" entre la criminalidad y la tasa de homicidios
df['percepcion_seguridad'] = (df['valoracion_criminalidad'] + df['valoracion_homicidios']) / 2
df['percepcion_seguridad']

0        8.260975
1        8.376973
2        8.912742
3        9.091575
4        7.887052
           ...
19995    3.338003
19996    3.503134
19997    2.845102
19998    2.276280
19999    2.828445
Name: percepcion_seguridad, Length: 20000, dtype: float64

### Estado civil

Se limpian los valores de estado civil, siendo soltero/a para los menores de 18 años, y el resto de valores se mantienen.

In [45]:
df.loc[df['edad'] < 18, 'estado_civil'] = 'soltero/a'
df[df['edad'] < 18]['estado_civil'].unique()

array(['soltero/a'], dtype=object)

### Nivel de estudios

Se limpian los valores de estudios que por edad no son coherentes con el máximo nivel de estudios alcanzado.

In [46]:
df['estudios'].unique().tolist()

['primero_secundaria',
 'educacion_superior',
 'primaria',
 'segundo_secundaria_general',
 'analfabetos',
 'estudios_primarios_incompletos',
 'segundo_secundaria_profesional']

In [47]:
# Se ordenan los niveles de educación de mayor a menor nivel
ordered_education = ['educacion_superior',
                     'segundo_secundaria_profesional',
                     'segundo_secundaria_general',
                     'primero_secundaria',
                     'primaria',
                     'estudios_primarios_incompletos',
                     'analfabetos']

In [48]:
# Se recorre todo el dataframe para comprobar registro por registro el nivel de estudios alcanzado por cada persona en función de su edad.
iterator = 0 # Iterador entre profesional y general en secundaria
for index, row in df.iterrows():
    # Comprobamos el nivel de estudios máximo al que puede obtar por su edad

    if row['edad'] < 10 and ordered_education.index(row['estudios']) < 5:
        # Si es menor de 10, los máximos estudios alcanzados son estudios primarios incompletos
        df.loc[index, 'estudios'] = ordered_education[5]

    if row['edad'] < 12 and ordered_education.index(row['estudios']) < 4:
        # Si es menor de 12, los máximos estudios alcanzados son primaria
        df.loc[index, 'estudios'] = ordered_education[4]

    elif row['edad'] < 16 and ordered_education.index(row['estudios']) < 3:
        # Si es menor de 16, los máximos estudios alcanzados son primero de secundaria
        df.loc[index, 'estudios'] = ordered_education[3]

    elif row['edad'] < 18 and ordered_education.index(row['estudios']) < 2:
        # Si es menor de 18, los máximos estudios alcanzados son segundo de secundaria
        df.loc[index, 'estudios'] = ordered_education[1 + iterator]
        iterator = 1 if iterator == 0 else 0 # Cambia entre profesional y general para la siguiente iteración

In [49]:
df[df['edad'] < 23]['estudios'].unique()

array(['primaria', 'educacion_superior', 'primero_secundaria',
       'estudios_primarios_incompletos', 'analfabetos',
       'segundo_secundaria_profesional', 'segundo_secundaria_general'],
      dtype=object)

### Salario anual

Se establece un salario 0 para menores de 16 años.

In [50]:
df.loc[df['edad'] < 16, 'salario_anual'] = 0

### Horas trabajadas al mes

Se establece un valor de 0 horas trabajadas al mes para menores de 16 años.

In [51]:
df.loc[df['edad'] < 16, 'horasTrabajadas_mes'] = 0

### Actividad física

Se establece una actividad física `nivel_bajo` para mayores de 75 años.

In [52]:
df.loc[df['edad'] > 75, 'actividad_fisica'] = 'nivel_bajo'

### Adecuación de columnas

Se eliminará información redundante de algunas columnas.

In [53]:
df

,comunidad_autonoma,edad,genero,actividad_fisica,asistencia_cine,asistencia_directos,asistencia_cultural,asistencia_deporte,dias_alta_contaminacion,homicidios_100mhabit,...,horasTrabajadas_mes,salario_anual,satisf_hospitales,satisf_dentistas,satisf_especialistas,satisf_medGeneral,frecuencia_felicidad,valoracion_criminalidad,valoracion_homicidios,percepcion_seguridad
0,Extremadura,10,hombre,nivel_alto,no,no_puede,no,no,3.3774,0.0000,...,0.0000,0.0000,hospitales_satisfecho/a,dentistas_muy_satisfecho/a,especialistas_insatisfecho/a,medGeneral_satisfecho/a,muy_a_menudo,6.521951,10.000000,8.260975
1,Extremadura,18,mujer,nivel_alto,no,no,no_puede,no,1.4413,0.3082,...,127.4882,23284.5483,hospitales_insatisfecho/a,dentistas_satisfecho/a,especialistas_satisfecho/a,medGeneral_satisfecho/a,algunas_veces,7.243059,9.510887,8.376973
2,Extremadura,41,hombre,nivel_bajo,no,si,si,no,6.7861,0.0408,...,153.6451,21607.6075,hospitales_satisfecho/a,dentistas_muy_satisfecho/a,especialistas_satisfecho/a,medGeneral_satisfecho/a,muy_a_menudo,7.890233,9.935250,8.912742
3,Extremadura,17,mujer,nivel_alto,si,no,no,no,2.5476,0.5331,...,132.2961,29640.1647,hospitales_insatisfecho/a,dentistas_neutral,especialistas_satisfecho/a,medGeneral_satisfecho/a,muy_a_menudo,9.029180,9.153971,9.091575
4,Extremadura,75,hombre,nivel_bajo,no,no,si,si,4.7876,0.2332,...,131.8787,17538.1113,hospitales_satisfecho/a,dentistas_satisfecho/a,especialistas_insatisfecho/a,medGeneral_satisfecho/a,muy_a_menudo,6.144192,9.629912,7.887052
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,Ceuta,67,mujer,nivel_bajo,no,si,no,no,3.0801,5.6225,...,125.0744,27052.8314,hospitales_neutral,dentistas_neutral,especialistas_insatisfecho/a,medGeneral_muy_satisfecho/a,muy_a_menudo,5.598910,1.077096,3.338003
19996,Ceuta,61,hombre,nivel_alto,no,no,si,no,5.4394,6.2117,...,139.3246,27063.6210,hospitales_neutral,dentistas_muy_satisfecho/a,especialistas_muy_satisfecho/a,medGeneral_satisfecho/a,muy_a_menudo,6.864232,0.142036,3.503134
19997,Ceuta,19,hombre,nivel_bajo,no,no,si,no,1.4983,6.0124,...,161.5733,26024.0808,hospitales_satisfecho/a,dentistas_neutral,especialistas_muy_satisfecho/a,medGeneral_satisfecho/a,algunas_veces,5.231879,0.458325,2.845102
19998,Ceuta,18,mujer,nivel_bajo,no,no,no,no,2.3925,5.9447,...,124.3620,19273.6664,hospitales_satisfecho/a,dentistas_satisfecho/a,especialistas_satisfecho/a,medGeneral_muy_satisfecho/a,algunas_veces,3.986794,0.565765,2.276280
19999,Ceuta,46,hombre,nivel_bajo,no_puede,no,no,no,2.2897,6.0490,...,187.4088,27875.2017,hospitales_neutral,dentistas_muy_satisfecho/a,especialistas_satisfecho/a,medGeneral_muy_satisfecho/a,muy_a_menudo,5.256649,0.400241,2.828445

In [54]:
# Eliminar el texto "hospitales_" de los registros tipo string en todas las columnas
df = df.applymap(lambda x: x.replace('hospitales_', '') if isinstance(x, str) else x)
df = df.applymap(lambda x: x.replace('dentistas_', '') if isinstance(x, str) else x)
df = df.applymap(lambda x: x.replace('especialistas_', '') if isinstance(x, str) else x)
df = df.applymap(lambda x: x.replace('medGeneral_', '') if isinstance(x, str) else x)

### Eliminación de columnas

Se eliminan columnas innecesarias para el análisis.

In [55]:
df.drop(columns=['valoracion_criminalidad'], inplace=True)
df.drop(columns=['valoracion_homicidios'], inplace=True)
df.drop(columns=['homicidios_100mhabit'], inplace=True)
df.drop(columns=['criminalidad_1000habit'], inplace=True)

In [56]:
df

,comunidad_autonoma,edad,genero,actividad_fisica,asistencia_cine,asistencia_directos,asistencia_cultural,asistencia_deporte,dias_alta_contaminacion,estudios,estado_civil,horasTrabajadas_mes,salario_anual,satisf_hospitales,satisf_dentistas,satisf_especialistas,satisf_medGeneral,frecuencia_felicidad,percepcion_seguridad
0,Extremadura,10,hombre,nivel_alto,no,no_puede,no,no,3.3774,primaria,soltero/a,0.0000,0.0000,satisfecho/a,muy_satisfecho/a,insatisfecho/a,satisfecho/a,muy_a_menudo,8.260975
1,Extremadura,18,mujer,nivel_alto,no,no,no_puede,no,1.4413,educacion_superior,casado/a,127.4882,23284.5483,insatisfecho/a,satisfecho/a,satisfecho/a,satisfecho/a,algunas_veces,8.376973
2,Extremadura,41,hombre,nivel_bajo,no,si,si,no,6.7861,primaria,soltero/a,153.6451,21607.6075,satisfecho/a,muy_satisfecho/a,satisfecho/a,satisfecho/a,muy_a_menudo,8.912742
3,Extremadura,17,mujer,nivel_alto,si,no,no,no,2.5476,primero_secundaria,soltero/a,132.2961,29640.1647,insatisfecho/a,neutral,satisfecho/a,satisfecho/a,muy_a_menudo,9.091575
4,Extremadura,75,hombre,nivel_bajo,no,no,si,si,4.7876,segundo_secundaria_general,soltero/a,131.8787,17538.1113,satisfecho/a,satisfecho/a,insatisfecho/a,satisfecho/a,muy_a_menudo,7.887052
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,Ceuta,67,mujer,nivel_bajo,no,si,no,no,3.0801,primaria,soltero/a,125.0744,27052.8314,neutral,neutral,insatisfecho/a,muy_satisfecho/a,muy_a_menudo,3.338003
19996,Ceuta,61,hombre,nivel_alto,no,no,si,no,5.4394,primaria,soltero/a,139.3246,27063.6210,neutral,muy_satisfecho/a,muy_satisfecho/a,satisfecho/a,muy_a_menudo,3.503134
19997,Ceuta,19,hombre,nivel_bajo,no,no,si,no,1.4983,primaria,soltero/a,161.5733,26024.0808,satisfecho/a,neutral,muy_satisfecho/a,satisfecho/a,algunas_veces,2.845102
19998,Ceuta,18,mujer,nivel_bajo,no,no,no,no,2.3925,primero_secundaria,soltero/a,124.3620,19273.6664,satisfecho/a,satisfecho/a,satisfecho/a,muy_satisfecho/a,algunas_veces,2.276280
19999,Ceuta,46,hombre,nivel_bajo,no_puede,no,no,no,2.2897,primero_secundaria,casado/a,187.4088,27875.2017,neutral,muy_satisfecho/a,satisfecho/a,muy_satisfecho/a,muy_a_menudo,2.828445

### Asignación de nivel general de felicidad

Se asigna un valor numérico de felicidad para cada registro, en función de los valores de anteriores parámetros.

In [57]:
def asaign_happiness_score(row):
    phisical_activity = row['actividad_fisica']
    cinema_attendance = row['asistencia_cine']
    direct_attendance = row['asistencia_directos']
    cultural_attendance = row['asistencia_cultural']
    sport_attendance = row['asistencia_deporte']
    ari_pollution = row['dias_alta_contaminacion']
    work_hours = row['horasTrabajadas_mes']
    anual_salary = row['salario_anual']
    hospital_satisfaction = row['satisf_hospitales']
    dentist_satisfaction = row['satisf_dentistas']
    specialist_satisfaction = row['satisf_especialistas']
    generalMed_satisfaction = row['satisf_medGeneral']
    security_perception = row['percepcion_seguridad']
    happiness_frecuency = row['frecuencia_felicidad']

    happiness_score = 0

    # Índice base de felicidad en función del último mes
    if happiness_frecuency == 'muy_a_menudo':
        appiness_score = 7
    elif happiness_frecuency == 'algunas_veces':
        appiness_score = 5
    else:
        appiness_score = 3

    # Variación en función de la actividad física.
    if phisical_activity == 'nivel_alto':
        appiness_score += 0.2
    elif phisical_activity == 'nivel_moderado':
        appiness_score -= 0.2

    # Variación en función de la asistencia a eventos.
    if cinema_attendance == 'si':
        appiness_score += 0.1
    elif cinema_attendance == 'no_puede':
        appiness_score -= 0.1

    if direct_attendance == 'si':
        appiness_score += 0.1
    elif direct_attendance == 'no_puede':
        appiness_score -= 0.1

    if cultural_attendance == 'si':
        appiness_score += 0.1
    elif cultural_attendance == 'no_puede':
        appiness_score -= 0.1

    if sport_attendance == 'si':
        appiness_score += 0.1
    elif sport_attendance == 'no_puede':
        appiness_score -= 0.1

    # Variación en función de la calidad del aire.
    if ari_pollution < 5:
        appiness_score += 0.5
    elif ari_pollution < 10:
        appiness_score += 0.2
    elif ari_pollution < 20:
        pass
    elif ari_pollution < 30:
        appiness_score -= 0.2
    else:
        appiness_score -= 0.5

    # Variación en función de las horas trabajadas al mes.
    if work_hours < 150:
        appiness_score += 0.2
    elif work_hours < 180:
        pass
    else:
        appiness_score -= 0.2

    # Variación en función del salario anual.
    if anual_salary < 20000:
        appiness_score -= 0.2
    elif anual_salary < 24000:
        appiness_score -= 0.1
    elif anual_salary < 28000:
        pass
    elif anual_salary < 32000:
        appiness_score += 0.1
    else:
        appiness_score += 0.2

    # Variación en función de la satisfacción sanitaria.
    if hospital_satisfaction == 'muy_satisfecho/a':
        appiness_score += 0.2
    elif hospital_satisfaction == 'satisfecho/a':
        appiness_score += 0.1
    elif hospital_satisfaction == 'neutral':
        pass
    elif hospital_satisfaction == 'insatisfecho/a':
        appiness_score -= 0.1
    else:
        appiness_score -= 0.2

    if dentist_satisfaction == 'muy_satisfecho/a':
        appiness_score += 0.2
    elif dentist_satisfaction == 'satisfecho/a':
        appiness_score += 0.1
    elif dentist_satisfaction == 'neutral':
        pass
    elif dentist_satisfaction == 'insatisfecho/a':
        appiness_score -= 0.1
    else:
        appiness_score -= 0.2

    if specialist_satisfaction == 'muy_satisfecho/a':
        appiness_score += 0.2
    elif specialist_satisfaction == 'satisfecho/a':
        appiness_score += 0.1
    elif specialist_satisfaction == 'neutral':
        pass
    elif specialist_satisfaction == 'insatisfecho/a':
        appiness_score -= 0.1
    else:
        appiness_score -= 0.2

    if generalMed_satisfaction == 'muy_satisfecho/a':
        appiness_score += 0.2
    elif generalMed_satisfaction == 'satisfecho/a':
        appiness_score += 0.1
    elif generalMed_satisfaction == 'neutral':
        pass
    elif generalMed_satisfaction == 'insatisfecho/a':
        appiness_score -= 0.1
    else:
        appiness_score -= 0.2

    # Variación en función de la percepción de seguridad.
    if security_perception < 3:
        appiness_score -= 0.2
    elif security_perception < 5:
        appiness_score -= 0.1
    elif security_perception < 6:
        pass
    elif security_perception < 8:
        appiness_score += 0.1
    else:
        appiness_score += 0.2

    return round(appiness_score, 1)

In [58]:
df['nivel_felicidad'] = df.apply(asaign_happiness_score, axis=1)

## Guardado de los datos

In [59]:
# Definir la ruta completa del archivo CSV
filename = 'cleaned_data.csv'
file_path = f'{data_basepath}..\\spain_dataframes\\{filename}'

# Guardar el DataFrame en un archivo CSV
df.to_csv(file_path, index=False)

print(f"DataFrame guardado exitosamente en '{filename}'")

DataFrame guardado exitosamente en 'cleaned_data.csv'